Clans:
  España:
    - BGMM
    - Ferrada
    - Esservil
    - Chxky
    - ElJarjas
    - drakos_
    - Fabroto
  Küdaulmapun:
    - Barrenas
    - 1an25
    - GuatonBairon
  LosBudas:
    - Caprileee
    - Zandsek
    - OneSip
    - chepito_
    - elwatonbb
    - NaShotZ
  LosBurgos: