Clans:
    españa:
        - BGMM
        - Ferrada
        - drakos_
        - 12x2
        - MaxBop
        - AbdulAkbar
        - Esservil
        - Fabroto
    budas:
        - Caprileee
        - OneSip
        - Zandsek
        - NaShotZ
        - chepito_
    losburgos:
        - ElJarjas
        - Chxky
    italia:
        - LAPianoM
        - Sensualon
        - DiosGeneroso
    mapuches:
        - 1an15
        - GuatonBairon
        - Barrenas
