name: Medievo
version: ${project.version}
main: com.bgmp.medievo.main
authors: [BGMM]
description: Medieval plugin
commands:
  randomtp:
    usage: /randomtp
    aliases: [rtp]
    description: Random teleport command
  create:
    usage: /create
    description: Creates a clan
  leave:
    usage: /leave
    description: Leaves you current clan
  invite:
    usage: /invite
    description: Invites someone to your actual clan
  accept:
    usage: /accept
    description: Accepts a clan invitiation
  cancel:
    usage: /cancel
    description: Cancels a clan invitation
  confirm:
    usage: /confirm
    description: Confirms an action
  deny:
    usage: /deny
    description: Denies can action
  reloadconfig:
    usage: /reloadconfig
    aliases: [rlconfig]
    description: Reloads the server config
  gamemode:
    usage: /gamemode
    description: Changes your gamemode
    aliases: [gm]
  broadcast:
    usage: /broadcast
    description: Broadcast to the server
    aliases: [br]
  permissions:
    medievo.broadcast:
      description: Allows you to send a broadcast message
      default: op
    medievo.gamemode:
      description: Allows you to change your gamemode
      default: op
    medievo.mod:
      descritpion: Allows you to get into mod mode
      default: op
