name: MedievoCore
version: ${project.version}
main: medievo.medievo.main
authors: [BGM]
description: Plugin core para El Medievo
commands:
  tpa:
    usage: /tpa
    description: Envía tpa a otro jugador
  tpaccept:
    usage: /tpaccept
    description: Acepta una solicitud de tpa entrante
  tpcancel:
    usage: /tpcancel
    description: Rechaza una solicitud de tpa entrante
  teleport:
    usage: /teleport
    description: Te teletransporta
    aliases: [tp]
  coords:
    usage: /coords
    description: Comparte tus coordenadas en el chat
  broadcast:
    usage: /broadcast
    aliases: [br]
    description: Envía un broadcast al server
  message:
    usage: /message
    description: Envía un mensaje privado
    aliases: [msg]
  gamemode:
    usage: /gamemode
    description: Cambiar gamemode
    aliases: [gm]
permissions:
  medievo.broadcast:
    description: Te permite enviar un broadcast al server
    default: op
  medievo.gamemode:
    description: Permite cambiar tu modo de juego
    default: op
  medievo.teleport:
    description: Permite teletransportarte
    default: op